apiVersion: apps/v1
kind: Deployment
metadata:
  name: saral-backend
spec:
  replicas: 10
  selector:
    matchLabels:
      app: saral-backend
  template:
    metadata:
      labels:
        app: saral-backend
    spec:
      containers:
      - name: saral-backend
        image: registry.hub.docker.com/saaral123/backendtest:{{IMAGE_TAG}}
        ports:
        - containerPort: 3005
        env:
        - name: PROFILE
          value: prod
        - name: PORT
          value: "3005"
        - name: MONGODB_URL
          value: "mongodb://10.0.31.152:27017,10.0.50.162:27017/prod_saral"
        - name: JWT_SECRET
          value: SARALDATA_NODE
        - name: MONGODB_POOL_SIZE
          value: "50"
        - name: MIN_MONGODB_POOL_SIZE
          value: "30"
        resources:
          limits:
            cpu: 2000m
            memory: 2Gi
          requests:
            cpu: 1000m 
            memory: 1Gi
      
        volumeMounts:
        - name: mongodb-data
          mountPath: /data/db
      volumes:
      - name: mongodb-data
        hostPath:
          path: /usr/local/mongodb/data/db
      restartPolicy: Always
      
---
apiVersion: v1
kind: Service
metadata:
  name: saral-backend
spec:
  selector:
    app: saral-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3005
  type: ClusterIP



  
  
  
      
