const constants = {
    APISTATUS: 'APISTATUS',
    OCR_LOCAL_RESPONSE: 'OCR_LOCAL_RESPONSE',
    LOGIN_PROCESS: 'login_process',
    GET_STUDENTS_EXAMS_LIST: 'get_students_exams_list',
    FILTERED_SCAN_DATA: 'filtered_scan_data',
    SAVE_SCAN_DATA: 'save_scan_data',
    SCAN_TYPE_DATA: 'SCAN_TYPE_DATA',
    ROI_DATA:'ROI_DATA',
    ABSENT_PRESENT_REDUCER:'ABSENT_PRESENT_REDUCER',
    SCANNED_DATA : 'SCANNED_DATA',
    SAVE_ABSENT_STUDENT_DATA: 'SAVE_ABSENT_STUDENT_DATA',
    GET_ABSENT_STUDENT_STATUS: 'GET_ABSENT_STUDENT_STATUS',
    GET_SCAN_STATUS: 'GET_SCAN_STATUS',
    MULTI_BRANDING:'MULTI_BRANDING'

};

export default constants;