import LocalizedStrings from 'react-native-localization'
export default strings = new LocalizedStrings({
    en: {
        cancel_text_caps: 'CANCEL',
        cancel_text: 'Cancel',
        ok_text: 'Ok',
        submit_text: 'SUBMIT',
        permission_deny: 'Permission Deny',
        you_have_no_permission_to_change_settings: 'You have no permission to change settings',
        open_settings: 'Open Settings',
        something_went_wrong_please_try_again: 'Something went wrong, Please try again.',
        message_text: 'Message',
        table_image_is_not_proper: 'Table image is not proper. Please try again.',
        saved_successfully: 'Saved Successfully',
        please_try_again: 'Please try again.',
        request_timeout_custom_message : "Request timed out. Please check your internet connection and retry.",
        you_seem_to_be_offline_please_check_your_internet_connection: 'Please check your internet connection.',
        yes_text: 'Yes',
        no_text: 'No',
        version_text: 'Version',
        give_permission_from_settings: 'Please give permission from Settings to use app',
        optional_update_available: 'A new update is available of App. Do you want to update now?',
        force_update_available: 'We have an updated version for you. Please Update to continue using App.',
        no_btn_text: 'No',
        yes_btn_text: 'Yes',

        test_id:'Test_ID',
        scan_status: 'Scan Status',
        save_status: 'Save Status',
        continue_scan:'Continue Scan',
        ongoing_scan: 'Ongoing Scan',
        save_scan:'Save All Scan',
        scan_text: 'Scan',
        permission_text: 'Permission',
        app_needs_permission: 'SaralData app needs access to your camera and storage',
        please_give_permission_to_use_app: 'Please give permission to use app',
        please_wait: 'Please wait...',
        student_roll: 'Student Roll No.',
        please_correct_student_roll: 'Please correct the Student Roll No.',
        login_text: 'Login',
        up_saralData: 'UP Saraldata',
        schoolId_text: 'School Id',
        password_text: 'Password',
        schoolid_password_doesnot_match: 'School Id or Password does not match',
        subject:'Subject',
        school_name: 'School',
        logout_text: 'Logout',
        are_you_sure_you_want_to_logout: 'Are you sure you want to logout?',
        please_select_below_details: 'Please select below details',
        select_text: 'Select',
        class_text: 'Class',
        section: 'Section',
        exam_sub: 'Exam Subject',
        exam_sub_date: 'Exam Subject - Date',
        exam_id: 'Exam ID',
        exam_date: 'Exam Date',
        submit_text: 'Submit',
        please_select_valid_section: 'Please select valid Section',
        please_select_class: 'Please select Class',
        please_select_section: 'Please select Section',
        please_select_date: 'Please select Date',
        please_select_sub: 'Please select Subject',
        total_marks: 'Total Marks',
        total_marks_secured: 'Total marks secured',
        summary_scanned_data: 'Scanned data summary',
        edit_text: 'Edit',
        save_text: 'Save',
        summary_text: 'Summary',
        please_correct_marks_data: 'Please edit and correct marks data.',
        student_roll_length_error: 'RollNo. should be 7 digit',
        sat_string: 'SAT',
        pat_string: 'PAT',
    }
})