openapi: 3.0.0
info:
  title: Saral Scanning layout specification
  description: >-
    The schema defines physicial layout representation of tabular layout that includes handwritten digits and OMR in the individual tabular cell.
  contact:
    name: ekstep foundation
    email: contact@ekstep.org
  version: 1.5.0
servers:
  - url: /none
paths: {}

components:
  schemas:
    layout:
      type: object
      description: defines the physical layout of the scanning area
      properties:
        version:
          type: string
          default: '1.5'
          description: layout detection version
        name:
          type: string
          description: layout name for human understanding
          example: Odisa SAT exam sheet format for class 2 to 5
        identifierPrefix:
          type: string
          description: Identifier it indicates the student or some ID. it can be studentID, RollNumber and VillageID etc.
          example: identifierPrefix= "ROLLNUMBER", identifierPrefix= "STUDENTID", identifierPrefix= "VILLAGEID"
        threshold:
          type: object
          description: layout threshold of width and height for POI(Point of Interest)
          properties:
            minWidth: 
              type: positiveInteger
              description: Minimum widht of layout for detection
            minHeight:
              type: positiveInteger
              description: Minimum height of layout for detection
        resultValidation: 
          type: object
          description: validate erroneous resultData and show error message when resultData does not match with regular expression .
          properties:
            validate:  
              type: object
              properties:
                regExp:
                  type: string
                  description: regular expression to detect erroneous resultData
                errorMsg:
                  type: string
                  description: error message shows when resultData does not match with regular expression.
                pages:
                  type: positiveInteger
                  description: number of pages supported by layout. Optional feild , to be used for multi-page layouts.
                  example: 3
                cells:
                  type: array
                  items:
                    $ref: '#/components/schemas/cell'
                  minItems: 1

        resultScreenLabels:
          type: object
          description: Result screen labels display table heading of layout.
          properties:
            id:
              type: string
              description: Identifier of layout .
            sr_no:
              type: string
              description: Sequence Number .
            questions:
              type: string
              description: It displays the field of layout .
            marks:
              type: string
              description:  It displays the value of layout .
    
        idValidation: 
          type: object
          description: validate erroneous Id and show an error message when the predicted Id does not match with the regular expression.
          properties:
            validate: 
              type: object
              properties:
                regExp:
                  type: string
                  description: regular expression to detect erroneous resultData
                  example: "^[0-9]{7}$"
                errorMsg: 
                  type: string
                  description: error message shows when resultData does not match with regular expression.
                  example: "Student I'd exceeds the limit"

    
    cell:
      type: object
      description: each logical area on the layout that needs to be scanned
      properties:
        cellId:
          type: string
          description: unique identity of the cell
        page:
          type: positiveInteger
          description: page number this cell belongs to. This field is added to support Multi-Page layouts.
          example: 2
        omrOptions:
          type: array
          description: list of values for omr selection in the cell. When multiple omr's present in a cell these values are 
            used in the order of index. If single omr present , two values for unselected omr and selected omr respectively.
            This is optional element. If not present index of omr will be used a value.
          example: ['A','B','C','D','E','F']
        rois:
          $ref: '#/components/schemas/rois'
        render:
          $ref: '#/components/schemas/renderingInformation'
        format:
          $ref: '#/components/schemas/formattingInformation'
        validate:
          $ref: '#/components/schemas/validationInformation'
        consolidatedPrediction:
          description: |
            consolidated prediction of all the rois with in a cell. 
            This is mandatory on the response sent to backend.
          type: string
        trainingDataSet:
          type: array
          description: |
            Training Data Set of each roi mat images in base 64 encoding.
            This data will be useful to train and optimise ML models.
          items:
            type: string

    
    renderingInformation:
      type: object
      description: should be used to render the layout for visualization and data correction.
      properties:
        index:
          type: number
          description: display index on the view
    
    formattingInformation:
      type: object
      description: represents logical purpose of the cell.
      properties:
        name:
          type: string
          description: human understandable description that explain cell purpose
          example: roll number
        value:
          type: string
          description: extracted resultData will be reported under this key. Be wise with the name
          example: rollNumber
          
    validationInformation:
      type: object
      description: validation rules thats needs to be applied on the cell level.
      properties:
        regExp:
          type: string
          description: regular expression to detect erroneous resultData
        errorMsg:
          type: string
          description: error message shows when resultData does not match with regular expression.
  
    rois:
      type: array
      items:
        $ref: '#/components/schemas/roi'
        minItems: 1
  
    roi:
      type: object
      description: a scanning area defined on the image. Scanning application will extract the result based upon 'roiId' and update the 'result' key
      required:
        - roiId
        - extractionMethod
        - roi
      properties:
        roiId:
          type: string
          description: unique roi identifier
        index:
          type: number
          description: index of roi in a cell area
          default: 0
        extractionMethod:
          type: string
          example: NUMERIC_CLASSIFICATION
          enum:
            - NUMERIC_CLASSIFICATION
            - CELL_OMR
            - BLOCK_ALPHANUMERIC_CLASSIFICATION
        rect:
          $ref: '#/components/schemas/rect'
        result:
          $ref: '#/components/schemas/extractedResult'

    rect:
      type: object
      description: rectangular area on the image frame
      required:
        - top
        - left
        - bottom
        - right
      properties:
        top:
          type: number
          description: x-coordinate of the ROI on the image
        left:
          type: number
          description: y-coordinate of the ROI on the image
        bottom:
          type: number
          description: x-coordinate of the ROI on the image
        right:
          type: number
          description: y-coordinate of the ROI on the image
          
    extractedResult:
      type: object
      description: result of data extraction
      properties:
        prediction:
          type: number
          description: detected data
        confidence:
          type: number
          description: degree of confidence regarding the prediction
    